name: Code formatting

on:
  pull_request:
    branches: 
      - main
    types: [closed]

jobs:
  black-formatting:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable
        with:
          options: "--verbose"
          src: "./txpipe"      
      - name: Commit formatted code
        run: |
          git config --global user.name 'Automatic formatter'
          git config --global user.email 'joezuntz@users.noreply.github.com'
          # commit only if there are no changes
          git diff --quiet || git commit -am "Format code with black"
          # okay if there are no changes
          git push
